import { Job } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: 'e9b1e36d-8b49-49fd-a8fd-9edb8ad2f68e',
    companyId: 'ab1d1ff0-4e29-4d4b-b9a1-7a385e9ecb62',
    company: {
      id: 'ab1d1ff0-4e29-4d4b-b9a1-7a385e9ecb62',
      name: 'HireFlow Core Engine',
      slug: 'hireflow-core',
      websiteUrl: 'https://hireflow.example.com',
      industry: 'Enterprise Software',
      location: 'Bengaluru, India',
    },
    title: 'Senior .NET Backend Architect',
    slug: 'senior-dotnet-backend-architect',
    description: `We are seeking an experienced Senior .NET Backend Architect to design, scale, and maintain our enterprise recruitment microservice platform built with .NET 10 LTS, ASP.NET Core Web API, and PostgreSQL.

Key Responsibilities:
- Design distributed RESTful APIs and asynchronous outbox event-driven architectures.
- Optimize Entity Framework Core 10 queries, PostgreSQL indexing, and Redis distributed caching.
- Implement robust security controls including JWT authentication, refresh-token rotation, and rate limiting.
- Write unit, integration, and performance benchmarks using xUnit and BenchmarkDotNet.`,
    location: 'Bengaluru / Remote',
    employmentType: 'FullTime',
    workMode: 'Hybrid',
    experienceMinYears: 5,
    experienceMaxYears: 9,
    salaryMin: 2800000,
    salaryMax: 3600000,
    currency: 'INR',
    skills: ['C#', '.NET 10', 'ASP.NET Core', 'PostgreSQL', 'Redis', 'Docker'],
    status: 'Published',
    createdByUserId: 'usr-admin-1',
    publishedAtUtc: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAtUtc: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAtUtc: new Date().toISOString(),
    canApply: true,
  },
  {
    id: 'f82a9110-33bc-42e1-912a-39048a01fe22',
    companyId: 'comp-vercel-01',
    company: {
      id: 'comp-vercel-01',
      name: 'Vercel Ecosystem Labs',
      slug: 'vercel-labs',
      websiteUrl: 'https://vercel.com',
      industry: 'Cloud Platform',
      location: 'Remote',
    },
    title: 'Staff Frontend Engineer (React & TypeScript)',
    slug: 'staff-frontend-engineer-react-ts',
    description: `Join our core UI engineering group building high-performance, accessible single-page web applications using React 18/19, TypeScript, Vite, TanStack Query, and Tailwind CSS.

Key Responsibilities:
- Architect reusable component libraries, design system tokens, and global state management.
- Implement strict client-side validation using React Hook Form and Zod.
- Integrate Axios interceptors for automatic JWT refresh-token rotation and correlation tracking.
- Optimize client-side web vitals, bundle sizes, and lighthouse accessibility scores.`,
    location: 'Remote / India',
    employmentType: 'FullTime',
    workMode: 'Remote',
    experienceMinYears: 4,
    experienceMaxYears: 8,
    salaryMin: 2400000,
    salaryMax: 3200000,
    currency: 'INR',
    skills: ['React 18', 'TypeScript', 'Vite', 'Tailwind CSS', 'TanStack Query', 'Zod'],
    status: 'Published',
    createdByUserId: 'usr-recruiter-1',
    publishedAtUtc: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAtUtc: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAtUtc: new Date().toISOString(),
    canApply: true,
  },
  {
    id: 'c749021e-1903-4412-a120-192a83918b99',
    companyId: 'comp-cloud-02',
    company: {
      id: 'comp-cloud-02',
      name: 'CloudScale Infrastructure',
      slug: 'cloudscale',
      websiteUrl: 'https://cloudscale.example.com',
      industry: 'DevOps & Infrastructure',
      location: 'Hyderabad, India',
    },
    title: 'Principal DevOps & Platform Engineer',
    slug: 'principal-devops-platform-engineer',
    description: `We are looking for a DevOps leader to manage multi-service deployment pipelines, Docker containerization, Kubernetes clusters, and OpenTelemetry monitoring acrossRender and AWS cloud targets.

Key Responsibilities:
- Build automated CI/CD pipelines using GitHub Actions with strict test gating and image security scanning.
- Containerize ASP.NET Core microservices and React static assets with Docker multi-stage builds.
- Configure Redis distributed rate limiting and PostgreSQL connection pooling.`,
    location: 'Hyderabad / Hybrid',
    employmentType: 'FullTime',
    workMode: 'Hybrid',
    experienceMinYears: 6,
    experienceMaxYears: 12,
    salaryMin: 3000000,
    salaryMax: 4200000,
    currency: 'INR',
    skills: ['Docker', 'Kubernetes', 'Terraform', 'GitHub Actions', 'OpenTelemetry', 'AWS'],
    status: 'Published',
    createdByUserId: 'usr-admin-1',
    publishedAtUtc: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAtUtc: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAtUtc: new Date().toISOString(),
    canApply: true,
  },
  {
    id: 'd10293a4-5511-47bb-b998-1290349f8011',
    companyId: 'comp-design-03',
    company: {
      id: 'comp-design-03',
      name: 'DesignCraft Studios',
      slug: 'designcraft',
      websiteUrl: 'https://designcraft.example.com',
      industry: 'Digital Product Design',
      location: 'Mumbai, India',
    },
    title: 'Product Designer (Design Systems)',
    slug: 'product-designer-design-systems',
    description: `Shape the visual identity and user interface components for enterprise web and mobile recruitment tools. Work closely with frontend engineers to translate Figma specs into clean Tailwind CSS UI tokens.`,
    location: 'Mumbai / Hybrid',
    employmentType: 'FullTime',
    workMode: 'Hybrid',
    experienceMinYears: 3,
    experienceMaxYears: 6,
    salaryMin: 1800000,
    salaryMax: 2400000,
    currency: 'INR',
    skills: ['Figma', 'UI/UX', 'Design Systems', 'Tailwind CSS', 'User Research'],
    status: 'Published',
    createdByUserId: 'usr-recruiter-2',
    publishedAtUtc: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    createdAtUtc: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAtUtc: new Date().toISOString(),
    canApply: true,
  },
  {
    id: 'b9012384-66aa-4112-9981-120934810293',
    companyId: 'ab1d1ff0-4e29-4d4b-b9a1-7a385e9ecb62',
    company: {
      id: 'ab1d1ff0-4e29-4d4b-b9a1-7a385e9ecb62',
      name: 'HireFlow Core Engine',
      slug: 'hireflow-core',
      websiteUrl: 'https://hireflow.example.com',
      industry: 'Enterprise Software',
      location: 'Bengaluru, India',
    },
    title: 'Full-Stack Software Engineer (.NET & React)',
    slug: 'fullstack-software-engineer-dotnet-react',
    description: `Deliver end-to-end features across C# ASP.NET Core microservices and React TypeScript web applications. Implement transactional outbox publishing, search filters, and real-time dashboard analytics.`,
    location: 'Bengaluru / Onsite',
    employmentType: 'FullTime',
    workMode: 'Onsite',
    experienceMinYears: 2,
    experienceMaxYears: 5,
    salaryMin: 1600000,
    salaryMax: 2200000,
    currency: 'INR',
    skills: ['C#', 'ASP.NET Core', 'React', 'TypeScript', 'PostgreSQL'],
    status: 'Published',
    createdByUserId: 'usr-admin-1',
    publishedAtUtc: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAtUtc: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAtUtc: new Date().toISOString(),
    canApply: true,
  },
  {
    id: 'a9102938-77bb-4112-9981-102938471029',
    companyId: 'comp-scale-04',
    company: {
      id: 'comp-scale-04',
      name: 'TechScale Global',
      slug: 'techscale',
      websiteUrl: 'https://techscale.example.com',
      industry: 'Fintech & Cloud',
      location: 'Remote',
    },
    title: 'Lead Engineering Manager (Microservices)',
    slug: 'lead-engineering-manager-microservices',
    description: `Lead a team of 8+ backend and frontend software engineers developing scalable distributed web applications. Oversee architectural decisions, code reviews, and delivery milestones.`,
    location: 'Remote',
    employmentType: 'FullTime',
    workMode: 'Remote',
    experienceMinYears: 7,
    experienceMaxYears: 14,
    salaryMin: 3500000,
    salaryMax: 4800000,
    currency: 'INR',
    skills: ['Engineering Leadership', 'Microservices', 'System Design', 'Agile', 'Mentorship'],
    status: 'Published',
    createdByUserId: 'usr-recruiter-1',
    publishedAtUtc: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    createdAtUtc: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAtUtc: new Date().toISOString(),
    canApply: true,
  },
];
